/**
 * ⚠️ SYNTHETIC DEMO DATA — NOT REAL.
 *
 * The 18 district *names* are real (they are Hong Kong's actual administrative
 * districts). Everything else in this file is invented:
 *
 * - The geometry is **schematic**, not cartographic. Districts are laid out in
 *   roughly their real relative positions — Hong Kong Island south, Kowloon in the
 *   middle, New Territories north — as simple blobs. It is deliberately *not* a
 *   coastline: pretending to be one would be worse than obviously not being one.
 *   Replace with Lands Department open data (`landsd.gov.hk`) before shipping.
 * - Every observation is generated by a seeded PRNG. See `observations.ts`.
 *
 * Nothing here may reach a screen without the demo banner that says so.
 */

export const SYNTHETIC = "SYNTHETIC — demo fixture, not real data" as const;

export type Region = "Hong Kong Island" | "Kowloon" | "New Territories";

export interface DemoDistrict {
  readonly id: string;
  readonly nameEn: string;
  readonly nameZh: string;
  readonly region: Region;
  /** Schematic centre in the demo's own 0–100 coordinate space. */
  readonly cx: number;
  readonly cy: number;
  /** Half-extents of the blob, same space. */
  readonly rx: number;
  readonly ry: number;
  /** Seed offset so each district gets a stable but distinct series. */
  readonly seed: number;
}

/**
 * Laid out on a 0–100 × 0–100 canvas. y grows downward (SVG convention), so the
 * New Territories sit at low y and Hong Kong Island at high y.
 */
export const DEMO_DISTRICTS: readonly DemoDistrict[] = [
  // ── New Territories (north) ──
  { id: "HK-N",   nameEn: "North",              nameZh: "北區",     region: "New Territories", cx: 52, cy: 12, rx: 13, ry: 7, seed: 101 },
  { id: "HK-YL",  nameEn: "Yuen Long",          nameZh: "元朗區",   region: "New Territories", cx: 24, cy: 18, rx: 13, ry: 8, seed: 102 },
  { id: "HK-TP",  nameEn: "Tai Po",             nameZh: "大埔區",   region: "New Territories", cx: 74, cy: 20, rx: 12, ry: 8, seed: 103 },
  { id: "HK-TM",  nameEn: "Tuen Mun",           nameZh: "屯門區",   region: "New Territories", cx: 12, cy: 32, rx: 10, ry: 8, seed: 104 },
  { id: "HK-TW",  nameEn: "Tsuen Wan",          nameZh: "荃灣區",   region: "New Territories", cx: 34, cy: 34, rx: 10, ry: 6, seed: 105 },
  { id: "HK-ST",  nameEn: "Sha Tin",            nameZh: "沙田區",   region: "New Territories", cx: 58, cy: 32, rx: 12, ry: 7, seed: 106 },
  { id: "HK-SK",  nameEn: "Sai Kung",           nameZh: "西貢區",   region: "New Territories", cx: 84, cy: 38, rx: 11, ry: 9, seed: 107 },
  { id: "HK-KT2", nameEn: "Kwai Tsing",         nameZh: "葵青區",   region: "New Territories", cx: 30, cy: 46, rx: 9,  ry: 6, seed: 108 },
  { id: "HK-IS",  nameEn: "Islands",            nameZh: "離島區",   region: "New Territories", cx: 12, cy: 62, rx: 10, ry: 9, seed: 109 },

  // ── Kowloon (middle) ──
  { id: "HK-SSP", nameEn: "Sham Shui Po",       nameZh: "深水埗區", region: "Kowloon", cx: 45, cy: 52, rx: 8, ry: 5, seed: 201 },
  { id: "HK-WTS", nameEn: "Wong Tai Sin",       nameZh: "黃大仙區", region: "Kowloon", cx: 62, cy: 50, rx: 8, ry: 5, seed: 202 },
  { id: "HK-KC",  nameEn: "Kowloon City",       nameZh: "九龍城區", region: "Kowloon", cx: 56, cy: 59, rx: 8, ry: 5, seed: 203 },
  { id: "HK-KwT", nameEn: "Kwun Tong",          nameZh: "觀塘區",   region: "Kowloon", cx: 73, cy: 57, rx: 9, ry: 6, seed: 204 },
  { id: "HK-YTM", nameEn: "Yau Tsim Mong",      nameZh: "油尖旺區", region: "Kowloon", cx: 44, cy: 63, rx: 8, ry: 5, seed: 205 },

  // ── Hong Kong Island (south) ──
  { id: "HK-CW",  nameEn: "Central and Western", nameZh: "中西區",  region: "Hong Kong Island", cx: 38, cy: 78, rx: 10, ry: 5, seed: 301 },
  { id: "HK-WCH", nameEn: "Wan Chai",            nameZh: "灣仔區",  region: "Hong Kong Island", cx: 56, cy: 77, rx: 8,  ry: 5, seed: 302 },
  { id: "HK-E",   nameEn: "Eastern",             nameZh: "東區",    region: "Hong Kong Island", cx: 75, cy: 76, rx: 11, ry: 5, seed: 303 },
  { id: "HK-S",   nameEn: "Southern",            nameZh: "南區",    region: "Hong Kong Island", cx: 55, cy: 90, rx: 16, ry: 6, seed: 304 },
];

/**
 * Turn a district's extents into a closed blob path. Deterministic: the same
 * district always produces the same outline, so the map doesn't twitch between
 * renders. Twelve points around an ellipse with a seeded wobble — enough to read as
 * a landmass rather than a rectangle, without claiming to be a coastline.
 */
export function districtPath(d: DemoDistrict): string {
  const POINTS = 12;
  let s = d.seed * 7919;
  const next = (): number => {
    s = (s * 1103515245 + 12345) & 0x7fffffff;
    return s / 0x7fffffff;
  };

  const pts: string[] = [];
  for (let i = 0; i < POINTS; i += 1) {
    const angle = (i / POINTS) * Math.PI * 2;
    const wobble = 0.82 + next() * 0.3;
    const x = d.cx + Math.cos(angle) * d.rx * wobble;
    const y = d.cy + Math.sin(angle) * d.ry * wobble;
    pts.push(`${x.toFixed(2)},${y.toFixed(2)}`);
  }
  return `M${pts.join("L")}Z`;
}
